# Generated by Django 5.0.6 on 2024-06-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clas_id', models.SmallIntegerField()),
                ('class_name', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('teacher', models.CharField(max_length=20)),
                ('enrollnment', models.SmallIntegerField()),
                ('room_number', models.SmallIntegerField()),
                ('class_duration', models.CharField(max_length=20)),
                ('meeting_days', models.CharField(max_length=20)),
                ('class_rep', models.CharField(max_length=20)),
                ('class_capacity', models.SmallIntegerField()),
            ],
        ),
    ]
