# Generated by Django 5.0.6 on 2024-07-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classperiod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('course', models.CharField(max_length=30)),
                ('classroom', models.CharField(max_length=25)),
                ('day_of_the_week', models.CharField(max_length=15)),
                ('total_students', models.PositiveIntegerField()),
                ('trainer_name', models.CharField(max_length=30)),
                ('trainers_assistant_name', models.CharField(max_length=30)),
                ('number_of_hours', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
