# Generated by Django 5.0.6 on 2024-08-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('student', '0002_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classe',
            field=models.ManyToManyField(to='classes.class'),
        ),
    ]
