# Generated by Django 5.0.6 on 2024-08-20 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
    ]
